# This is the testing environment.
name: ramp_velo_challenge
dependencies:
  - bcrypt
  - bokeh
  - boto3
  - click
  - flake8
  - Flask
  - Flask-Login
  - Flask-SQLAlchemy
  - Flask-Wtf
  - gitpython
  - itsdangerous
  - nbconvert
  - numpy
  - pandas
  - pyyaml
  - pytest
  - pytest-cov
  - psycopg2
  - sqlalchemy
  - tornado==5.1.1  # downgrade tornado for nbconvert and should be fix
  - pip:
    - codecov
    - git+https://github.com/paris-saclay-cds/ramp-workflow.git
    - Flask-Mail
